### ISSUE TITLE
Slice size is cut with the angleMod calculation

### ISSUE THREAD

**Issue by Vitomir2** [snowPu/ngx-beautiful-charts#12]
Dear Sukanya,

I really like your project and I want to use it into mine. However, I already implemented it, but there is a small problem when the parents are only 2 and they are separated, e.g., 70% to 30%. You will see it in my example with the Bus and Train slices.

I think the problem comes from the calculation of this line -  76: const angleMod = (angle > 180 ) ? 360 - angle : angle; in the sunburst component.

Can you tell me how I can fix this or if you can do it ? Thank you in advance!

Here I attach a [screenshot.](https://drive.google.com/file/d/1cVaVpxYfdAk9uCZszO56H9cMCp2xN2k2/view?usp=sharing)

Best regards,
Vitomir

**Comment by snowPu** [comment]
Hey @Vitomir2 :)

Thank you for writing to me about the issue. 

Could you update the npm library and try again? It should be fixed :)

**Comment by rozalia1** [comment]
Hey @snowPu :)

Thank you for the response! Yes, it works good now.

Best regards,
Vitomir

**Comment by Vitomir2** [comment]
Hey @snowPu  :)

Thank you for your response and fast fixing! It works pretty well now and my circle (or part of circle) is filled.

Best regards,
Vitomir
